name: cache-vms
on:  
  workflow_dispatch:

env:
  GO_VERSION: '1.18'
permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none
jobs:

  cache-fedora-box:
    needs: image

    runs-on: macos-12
    timeout-minutes: 90
    env:
      RUN: ./hack/ci/run-fedora.sh
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Boot Virtual Machine
        run: make vagrant-up-fedora
      - name: Show environment information
        run: |
          $RUN kubectl wait --for=condition=ready --timeout=60s node 127.0.0.1
          $RUN kubectl get nodes -o wide
      - name: Set up git config
        run: |
          $RUN git config --global --add safe.directory /vagrant
      - uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c
        with:
          path: fedora.box
      - name: Saving Update Virtual Machine
        run: |
          vagrant package --output fedora.box


  cache-ubuntu-box:
    needs: image

    runs-on: macos-12
    timeout-minutes: 90
    env:
      RUN: ./hack/ci/run-ubuntu.sh
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Boot Virtual Machine
        run: make vagrant-up-ubuntu
      - name: Show environment information
        run: |
          $RUN kubectl wait --for=condition=ready --timeout=60s node ubuntu2204
          $RUN kubectl get nodes -o wide
      - name: Set up git config
        run: |
          $RUN git config --global --add safe.directory /vagrant
      - uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c
        with:
          path: ubuntu.box
      - name: Saving Update Virtual Machine
        run: |
          vagrant package --output ubuntu.box


  cache-flatcar-box:
   needs: image

   runs-on: macos-12
   timeout-minutes: 90
   env:
     RUN: ./hack/ci/run-flatcar.sh
   steps:
     - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
     - name: Vagrant box version
       id: vagrant-box
       run: |
         echo "::set-output name=version::$(curl -s  https://stable.release.flatcar-linux.net/amd64-usr/current/flatcar_production_vagrant.json | jq '.versions[0].version' | tr -d '".')"
       shell: bash
     - name: Upgrade vagrant box
       run: |
         ln -sf hack/ci/Vagrantfile-flatcar Vagrantfile
         vagrant box update
     - uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
       with:
         name: image
         path: .
     - name: Boot Virtual Machine
       run: make vagrant-up-flatcar
     - name: Show environment information
       run: |
         $RUN kubectl wait --for=condition=ready --timeout=600s node localhost
         $RUN kubectl get nodes -o wide
     - uses: actions/cache@f4278025ab0f432ce369118909e46deec636f50c
       with:
         path: flatcar.box
     - name: Saving Update Virtual Machine
       run: |
         vagrant package --output flatcar.box

